# -*- coding: utf-8 -*-
"""Evaluacion Parcial 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TrvpAD-DvsoyQQAY6tBlNAg7vbW4kpYL
"""

import numpy as np

lista = []
lista_datos = []
def gabar():

    edad = int(input("Ingrese su edad: "))
    print(" ")
    nombre = input("Ingrese su nombre: ")
    print(" ")
    print("Usted es de la Union Europea?")
    pertenece = int(input("1.- Si    2.- No  : "))
    if pertenece == 1:
        pertenece = 'Si'
    elif pertenece == 2:
        pertenece == 'No'
    print(" ")
    print("Ingrese su Estado civil")
    civil = int(input("1.- Soltero  2.- Casado  : "))
    if civil == 1:
        civil = 'Soltero'
    elif civil == 2:
        civil = 'Casado'

    if edad >= 15:
        print("Considere ingresar 8 caracteres")
        numeros = input("Ingrese el codigo numererico: ")
        print(" ")

        if len(numeros) == 8:
            print("Largo ingresado correcto")
            print(" ")

            print("Ingrese el codigo alfabetico")
            letras = input("Considere ingresar 3 caracteres: ")
            if len(letras) == 3:
                print("Largo ingresado correcto")
                print(" ")
                nif =[numeros+letras]
                datos = [edad,nombre,pertenece,civil]
                lista.append(nif)
                lista_datos.append(datos)
                #print(lista)
                #print(lista_datos)
            else:
                print("Largo incorrecto, intente nuevamente.")
                print(" ")
        else:
            print("Largo incorrecto, intente nuevamente.")
            print(" ")
    else:
        print("Usted debe ser mayor a 15 años")
        print(" ")


def buscar():
    codigo = input("Ingrese el NIF que busca: ")
    for i in range(len(lista)):
        if lista[i][0] == codigo:
            print("NIF encontrado")
            print(f"NIF: {lista[i][0]}")
            print(f"Edad: {lista_datos[0][0]}")
            print(f"Nombre: {lista_datos[0][1]}")
            print(f"Pertenece a la U.E: {lista_datos[0][2]}")
            print(" ")
            break
        else:
            print("NIF no encontrado.")
            print(" ")


def imprimir():
    print("---------------------")
    print("Certificado")
    print("---------------------")
    print(f"NIF: {lista[0][0]}")
    print("---------------------")
    print(f"Edad: {lista_datos[0][0]}")
    print("---------------------")
    print(f"Nombre: {lista_datos[0][1]}")
    print("---------------------")
    print(f"Pertenece a la U.E: {lista_datos[0][2]}")
    print("---------------------")
    print(f"Estado civil: {lista_datos[0][3]}")
    print("---------------------")
    print(" ")

import funciones as fn

    opcion = 0

    while True:
        print("--------Menu--------")
        print(" ")
        print("1.- Grabar")
        print("2.- Buscar")
        print("3.- Imprimir")
        print("4.- Salir")
        opcion = int(input("Ingrese una opcion: "))
        if opcion == 1:
            print(" ")
            fn.gabar()
        elif opcion == 2:
            print(" ")
            fn.buscar()
        elif opcion == 3:
            print(" ")
            fn.imprimir()
        elif opcion == 4:
            print("Gracias por usar nuestro programa!")
            print("Powered by Bayron Cortez Cheuquian \n Program Version: 2.13")
            print("Adios!")
            break
        else:
            print(" ")
            print("Opcion igresada fuera de rango.")